# Describe p2p targets in joint angle space (/swing, /boom, /arm, /bucket, /bucket_end) with rad unit.

p2p_targets:
  - [0.0, -0.5, 1.0, 0.0, 0.0]
  - [0.5, -0.2, 0.5, 0.3, 0.0]
  - [1.0, 0.0, -0.5, -0.3, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0]
